insert into car_brands (title) value ("Audi");
insert into car_brands (title) value ("BMW");
insert into car_brands (title) value ("Ford");
insert into car_brands (title) value ("Porsche");
insert into car_brands (title) value ("Fiat");
insert into car_models (carBrandId, title) values (1, "TT");
insert into car_models (carBrandId, title) values (1, "A7");
insert into car_models (carBrandId, title) values (1, "A8");
insert into car_models (carBrandId, title) values (2, "X5");
insert into car_models (carBrandId, title) values (2, "Z3");
insert into car_models (carBrandId, title) values (3, "Fiesta");
insert into car_models (carBrandId, title) values (3, "Focus");
insert into car_models (carBrandId, title) values (4, "Panamera");
insert into car_models (carBrandId, title) values (5, "Punto");
insert into users (firstName, lastName, email, password) values ("Mark", "Voronov", "m.voronov@gmail.com", 1234);
insert into users (firstName, lastName, email, password) values ("Pavlo", "Voronov", "p.voronov@gmail.com", 5678);
insert into users (firstName, lastName, email, password) values ("Anastasiia", "Melnyk", "a.melnyk@gmail.com", 91011);
insert into users (firstName, lastName, email, password) values ("Ivan", "Ivanov", "i.ivanov@gmail.com", 4321);
insert into users (firstName, lastName, email, password) values ("Stepan", "Stepanov", "s.stepanov@gmail.com", 1234);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (1, 1, 1, 250, 200);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (1, 2, 1, 30, 20);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (2, 2, 2, 100, 80);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (3, 1, 1, 1250, 1200);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (4, 4, 1, 10, 1);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (5, 5, 1, 714, 700);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (1, 5, 1, 550, 500);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (2, 1, 2, 70, 30);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (3, 1, 3, 36, 17);
insert into cars (userId, carBrandId, carModelId, mileage, initialMilleage) values (4, 1, 6, 250, 200);